version: '3.8'

services:
  php:
    image: alvicha/symfony-app:latest
    container_name: symfony_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - uploads_data:/var/www/html/public/img:rw
    depends_on:
      database:
        condition: service_healthy

  nginx:
    image: alvicha/symfony-nginx:latest
    container_name: symfony_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html:ro
      - uploads_data:/var/www/html/public/img:ro
    depends_on:
      php:
        condition: service_started

  database:
    image: mysql:8.0
    container_name: symfony_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: FitnessRoot1234
      MYSQL_DATABASE: proyecto
      MYSQL_USER: fitness
      MYSQL_PASSWORD: fitness1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 3

volumes:
  db_data:
  uploads_data:
   driver: local