name: Deploy Symfony API with MySQL and Nginx

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Clonar el repositorio
      - name: Checkout código
        uses: actions/checkout@v4

      # 3. Iniciar sesión en Docker Hub
      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Construir y subir la imagen de Symfony
      - name: Construir y subir imagen Symfony (PHP)
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/symfony-app:latest -f proyectoBack/docker_pi/php/Dockerfile proyectoBack/
          docker push ${{ secrets.DOCKER_USERNAME }}/symfony-app:latest

      # 5. Construir y subir la imagen de Nginx
      - name: Construir y subir imagen Nginx
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/symfony-nginx:latest -f proyectoBack/docker_pi/nginx.Dockerfile proyectoBack/
          docker push ${{ secrets.DOCKER_USERNAME }}/symfony-nginx:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      # 1. Checkout del código
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0 # Clona todo el historial del repo

      # 2. Verificar estructura del repositorio
      - name: Verificar estructura del repositorio
        run: |
          echo "Directorio actual: $(pwd)"
          ls -R

      # 3. Transferir el archivo compose.yml a servidor remoto
      - name: Transferir compose.yml al servidor remoto
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          source: ${{ github.workspace }}/proyectoBack/compose.yml
          target: ~/deploy/
          strip_components: 3

      # 4. Desplegar en un servidor remoto
      - name: Desplegar en servidor remoto
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          script: |
            sudo chmod 666 /var/run/docker.sock
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            
            docker-compose -f /home/${{ secrets.REMOTE_USER }}/deploy/workspace/compose.yml pull
            docker-compose -f /home/${{ secrets.REMOTE_USER }}/deploy/workspace/compose.yml down
            docker-compose -f /home/${{ secrets.REMOTE_USER }}/deploy/workspace/compose.yml up -d --force-recreate

      - name: Crear la base de datos si no existe y ejecutar migraciones
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          script: |
            docker exec symfony_app php bin/console doctrine:database:create --if-not-exists
            docker exec symfony_app php bin/console doctrine:migrations:migrate --no-interaction